export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';


export const CREATE_OPTION = 'CREATE_OPTION';
export const LOAD_OPTIONS_SUCCESS = 'LOAD_OPTIONS_SUCCESS';
export const LOAD_TEMPLATES_SUCCESS = 'LOAD_TEMPLATES_SUCCESS';
export const CHOICE_CHANGED_SUCCESS = 'CHOICE_CHANGED_SUCCESS';

export const SAVE_RECOVERABLE_FAILURE = 'SAVE_RECOVERABLE_FAILURE';

export const LOAD_SETTINGS = 'LOAD_SETTINGS';

export const UPDATE_CONFIGURATOR_SUCCESS = 'UPDATE_CONFIGURATOR_SUCCESS';
